### ISSUE TITLE
Add UI tests for other fragments

### ISSUE THREAD

**Issue by nout-kleef** [SDP-group22/Helio-app#118]
Similar to what we have for the sliders UI tests

**Comment by nout-kleef** [comment]
- [x] blinds control fragment
- [ ] schedule fragment
- [ ] sensors fragment
- [ ] settings fragment

**Comment by adamb56789** [comment]
Did you know about Record Espresso Test? I just discovered it by accident. We could use it to generate a lot of tests very easily for any functionality that hasn't been covered yet.
![image](https://user-images.githubusercontent.com/17644409/111992286-21a18000-8b0d-11eb-8db9-70faf1da0349.png)

**Comment by nout-kleef** [comment]
Nope this is new to me. I added more tests with #157, but I guess we could use that if we have time left before the deadline
