### ISSUE TITLE
Improve motor page based on feedback

### ISSUE THREAD

**Issue by adamb56789** [SDP-group22/Helio-app#141]
Thomas wrote the following:

"The page doesnt utilise the available space very well, i.e. icon selection takes up a lot of space but the name and ip address fields could be larger. The icon selection can extend so far as to obscure the schedule page navigation button. It would be nice if it was possible to scroll through the icons rather than them all appearing in a long line."

- [ ] Do something to stop the icon selection from taking up so much space. Simply reducing the maximum allowed height of it might be enough. [See this search](https://www.google.com/search?q=android+spinner+dropdown+size&rlz=1C1CHBF_en-GBGB920GB920&sxsrf=ALeKk02yaREjsjCUg7sgRlr4i5T4mF8umQ%3A1616194138029&ei=WipVYKGlAYmigQaG7J7YCw&oq=android+spinner+dropdown+size&gs_lcp=Cgdnd3Mtd2l6EAMyAggAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgAEEcQsAM6BAgjECc6BAgAEEM6BQgAEJECOgcIABCxAxBDOgUIABCxA1CYQVi0amDDa2gBcAJ4AIABTIgBzgiSAQIxOJgBAKABAaoBB2d3cy13aXrIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwihuvCruL3vAhUJUcAKHQa2B7sQ4dUDCA0&uact=5) and [this stackoverflow](https://stackoverflow.com/questions/20597584/how-to-limit-the-height-of-spinner-drop-down-view-in-android).
- [ ] Resize other elements to make better use of space (OPTIONAL)

**Comment by Jeremy-hao** [comment]
I try to follow your method, it doesn't work. 
![image](https://user-images.githubusercontent.com/51730801/112119287-33ac1d00-8bf8-11eb-978d-6238983dc36a.png)

**Comment by Jeremy-hao** [comment]
And I also try to use the Field of the current class, it also doesn't work. Maybe we can create a dropdown_list.xml to solve it. But it will contradict the IconArrayAdapter.

**Comment by adamb56789** [comment]
I tried all the solutions and nothing worked
