### ISSUE TITLE
Reduce warnings

### ISSUE THREAD

**Issue by adamb56789** [SDP-group22/Helio-app#155]
Maybe one of the things we can put in the evaluation is how many warnings there are in Android studio. There are probably quite a lot, so it be good to reduce them as much as possible, and we can talk about this.

**Comment by TianYouX** [comment]
I have watched through all the files. There is only one warning other than "constructor or method is never used". Do we need to solve it or leave it there.
![image](https://user-images.githubusercontent.com/77977523/111950949-f4a99900-8b1d-11eb-96fa-6228dbeaa1ba.png)

**Comment by adamb56789** [comment]
There are 39 warnings at the moment.

Analyse -> Inspect code (include tests)
![image](https://user-images.githubusercontent.com/17644409/111967988-97e3b980-8af0-11eb-9793-1c3720c66087.png)

Fix them if you can, though it is ok to suppress them if they can't be fixed and aren't causing any problems.

**Comment by TianYouX** [comment]
![image](https://user-images.githubusercontent.com/77977523/111987122-c17cff00-8b49-11eb-876c-c4209f7ebee3.png)

**Comment by adamb56789** [comment]
The unused error on `getLightSensors(`) is because I made a mistake earlier. This should be used in line 80 of `SensorsSettingsFragment` in `addButtonOnCLickLight()` instead of `getMotionSensors()`. Can you fix this error?

**Comment by adamb56789** [comment]
Can you remove the other two unused methods though? If you ctrl click on them they have no uses. If you get rid of them I would say that we have no warnings.

The other warnings for unused resource can be ignored since we want to save those files anyway, and the spelling errors aren't actually errors.

**Comment by TianYouX** [comment]
Oh, I didn't see your comments just now. Just ignore this pull request.

**Comment by adamb56789** [comment]
When you are finished just request a review on whichever PR so we know you are done.
