### ISSUE TITLE
Perform coverage analysis and make tests if possible

### ISSUE THREAD

**Issue by adamb56789** [SDP-group22/Helio-app#160]
Check instrumented test coverage with this:
https://stackoverflow.com/questions/33393871/how-to-obtain-coverage-for-android-project-using-espresso-tests
Then if possible use this to create more tests to try to increase coverage:
![image](https://user-images.githubusercontent.com/17644409/112072280-64914100-8b69-11eb-91d3-bd4ebe967df0.png)

**Comment by Jeremy-hao** [comment]
![image](https://user-images.githubusercontent.com/51730801/112631903-70834880-8e72-11eb-84ac-9e5e1d5048ec.png)

**Comment by Jeremy-hao** [comment]
![Uploading image.png…]()

**Comment by Jeremy-hao** [comment]
![image](https://user-images.githubusercontent.com/51730801/112632220-cbb53b00-8e72-11eb-891e-ad8df1d0f138.png)

**Comment by Jeremy-hao** [comment]
It's good enough actually.
