### ISSUE TITLE
Demo 1 presentation

### ISSUE THREAD

**Issue by adamb56789** [SDP-group22/Helio-app#18]
Produce app section of demo 1 with screenshots or videos of the current state of the app. Probably needs coordination with tech team.

**Comment by Jeremy-hao** [comment]
What about the screenshots used in the demo report and then we can use all these screenshots to make a short video. The video also needs to have some personal descriptions added to it.

**Comment by nout-kleef** [comment]
After our group meeting this morning it seems this will require coordination with @Michael-Rimmer, both adding some slides to the presentation.

**Comment by adamb56789** [comment]
I sent some slides over to Michael
