### ISSUE TITLE
Make settings page, linked from main page

### ISSUE THREAD

**Issue by nout-kleef** [SDP-group22/Helio-app#35]

**Comment by adamb56789** [comment]
Settings should be a menu from clicking 3 dots in corner like normal

**Comment by adamb56789** [comment]
If you think of any settings that are needed, comment them here.
1. Connect to hub
2. Edit blinds - add/remove blinds, edit IP address (for now, we might do something else later), name, icon.

**Comment by adamb56789** [comment]
See the "Settings menu" section of #42 for details of what this should include.
