### ISSUE TITLE
Research high-contrast themes

### ISSUE THREAD

**Issue by nout-kleef** [SDP-group22/Helio-app#54]
find out what we need to do to make the app usable by a wide audience.

Specifically:

- how do we add an optional high-contrast theme for visually impaired people

**Comment by adamb56789** [comment]
- Android studio linter automatically tells warns you to use localisable layout tags for right to left layouts, and when you are using a string which is not in a string resource file.
- You make versions of `strings.xml` for different languages for translations.
- Android studio also has a "Translations Editor" to view each translation side by side, but it is not necessary

![image](https://user-images.githubusercontent.com/17644409/107634520-8d1c4600-6c61-11eb-83e0-46a17ad3335e.png)
![image](https://user-images.githubusercontent.com/17644409/107634685-d66c9580-6c61-11eb-873e-a9cd35efc6ae.png)

**Comment by nout-kleef** [comment]
There doesn't seem to be explicit support for "high-contrast" themes from Android itself. However, it would still be a nice feature to add for people who may have trouble using our UI.
I found some resources that describe how to add themes, and it seems quite straightforward:

- [themes vs styles](https://medium.com/androiddevelopers/android-styling-themes-vs-styles-ebe05f917578)
- [themes tutorial](https://developer.android.com/guide/topics/ui/look-and-feel/themes)
