### ISSUE TITLE
test app-hub connectivity with Ales

### ISSUE THREAD

**Issue by nout-kleef** [SDP-group22/Helio-app#67]
For the demo video and for our final product it is crucial that we are able to send data between the app and the hub.
I'm working together with Ales to ensure this works well

**Comment by nout-kleef** [comment]
@AlesRessler and I met today to try out sending requests from the app to the hub.
We ran into various issues:

- Although I was able to install Android Studio, the DICE machines do not allow us to enable hardware acceleration. This means that we can only use pure software emulation when running our app, which is incredibly slow (the device would not boot because of timeout).
- When we tried running the emulator locally instead, there was the obvious issue that the university's firewall does not allow any requests from outside the local network. Because the hub must remain inside the university network (to interact with motors and sensors), we had to find a way around this.
- In the end I got it working by running the `helio-hub` directly on the gateway server (`ssh.inf.ed.ac.uk`, which is not advised) and setting up an ssh tunnel: `ssh -L 8989:ssh.inf.ed.ac.uk:4310 <UUN>@ssh.inf.ed.ac.uk`

We'll meet again on Monday to conduct the connectivity tests and plan the demo video recording.

**Comment by adamb56789** [comment]
I tried to get the app to talk to the hub properly. The TLDR is that the API specification has changed, so it doesn't work.

**Comment by adamb56789** [comment]
If you are having trouble getting it to work/want to use the updated version, checkout this https://github.com/SDP-group22/Helio-app/tree/finish_api_connection for the app and this https://github.com/SDP-group22/helio-hub/pull/5 for the hub.

**Comment by nout-kleef** [comment]
Cheers Adam. Ales and I will meet again on Thursday to make the video, and we will check that everything is working before then.
