### ISSUE TITLE
Create manual testing plan

### ISSUE THREAD

**Issue by adamb56789** [SDP-group22/Helio-app#85]
A list of specifications that the app needs to satisfy such as "User can connect to a motor and move it to a target level" and "User can set the icon of a motor and it is displayed", and criteria to be judged such as "Responsiveness of the app to user actions" and "Design is aesthetically pleasing".

These tests will be performed on a physical device, with the hub running on a connected computer. Since testing the full system is hard given the circumstances, monitoring the hub's log will be considered sufficient. (We assume that what the hub does after that is beyond our control)

**Comment by adamb56789** [comment]
Teams -> app team -> files -> Manual testing.xlsx -> See both functional and non-functional testing tabs.

**Comment by nout-kleef** [comment]
There are two things I noticed that could be made more objective, but other than that these tests seem very useful.

1. for rows 20 and 21, "basic details" is not clearly defined (although we would probably agree when deciding between pass/fail)
2. for row 33, what would potentially be refreshed, and what changes are we considering here?

**Comment by adamb56789** [comment]
Made some changes to those tests.
